Create database Colegio;
USE Colegio;
CREATE TABLE SCHOOL (
    SchoolId INT PRIMARY KEY IDENTITY,
    SchoolName VARCHAR(50) NOT NULL,
    Description VARCHAR(1000),
    Address VARCHAR(100),
    Phone VARCHAR(50),
    PostCode VARCHAR(50),
    PostAddress VARCHAR(50)
);

CREATE TABLE CLASS (
    ClassId INT PRIMARY KEY IDENTITY,
    SchoolId INT FOREIGN KEY REFERENCES SCHOOL(SchoolId),
    ClassName VARCHAR(50) NOT NULL,
    Description VARCHAR(1000)
);

CREATE TABLE COURSE (
    CourseId INT PRIMARY KEY IDENTITY,
    CourseName VARCHAR(50) NOT NULL,
    SchoolId INT FOREIGN KEY REFERENCES SCHOOL(SchoolId),
    Description VARCHAR(1000)
);

CREATE TABLE STUDENT (
    StudentId INT PRIMARY KEY IDENTITY,
    ClassId INT FOREIGN KEY REFERENCES CLASS(ClassId),
    StudentName VARCHAR(100) NOT NULL,
    StudentNumber VARCHAR(20),
    TotalGrade FLOAT,
    Address VARCHAR(100),
    Phone VARCHAR(20),
    Email VARCHAR(100)
);

CREATE TABLE TEACHER (
    TeacherId INT PRIMARY KEY IDENTITY,
    SchoolId INT FOREIGN KEY REFERENCES SCHOOL(SchoolId),
    TeacherName VARCHAR(50) NOT NULL,
    Description VARCHAR(1000)
);

CREATE TABLE STUDENT_COURSE (
    StudentId INT FOREIGN KEY REFERENCES STUDENT(StudentId),
    CourseId INT FOREIGN KEY REFERENCES COURSE(CourseId),
    PRIMARY KEY (StudentId, CourseId)
);

CREATE TABLE TEACHER_COURSE (
    TeacherId INT FOREIGN KEY REFERENCES TEACHER(TeacherId),
    CourseId INT FOREIGN KEY REFERENCES COURSE(CourseId),
    PRIMARY KEY (TeacherId, CourseId)
);

CREATE TABLE GRADE (
    GradeId INT PRIMARY KEY IDENTITY,
    StudentId INT FOREIGN KEY REFERENCES STUDENT(StudentId),
    CourseId INT FOREIGN KEY REFERENCES COURSE(CourseId),
    Grade FLOAT,
    Comment VARCHAR(1000)
);